#   gem install mysql2
#   docker exec -it 251108badb0c mysql -u root -ppassword

default: &default
  adapter: mysql2
  database: zeroken_api
  username: root
  password: password
  host: db
  encoding: utf8

development:
  <<: *default
  database: zeroken_api_development

test:
  <<: *default
  database: zeroken_api_test

production:
  <<: *default
  database: zeroken_api_production
  username: zeroken_api